title: Networking Conference Deadlines # (Maintained by @albertgranalcoz)
# email: galberto@ethz.ch
description: Countdowns to top Networking conference deadlines
author: Albert Gran Alcoz

domain: "giacgiuliari.github.io"
baseurl: "/netdeadlines"

twitter_username: albertgran
twitter_hashtag: networking

github_username: albertgranalcoz
github_repo: netdeadlines

markdown: kramdown
ga_id: G-X2P0WXEN1V

include: ['_pages']
